from pathlib import Path

def rep(path, old, new):
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise SystemExit(f'missing expected text in {path}')
    p.write_text(text.replace(old, new, 1))

rep('radio-admin/dev/social-factory/index.html', '<div class="sf-video-frame"><video id="videoPreview" controls playsinline preload="metadata"></video><div id="previewLoading" class="sf-preview-loading">Loading secure preview…</div></div>\n              <div class="sf-video-facts">', '<div class="sf-video-frame"><video id="videoPreview" controls playsinline preload="metadata"></video><div id="previewLoading" class="sf-preview-loading">Select Preview Video to create a secure 15-minute preview.</div></div>\n              <div class="sf-form-actions"><button id="previewVideoButton" class="sf-button" type="button">Preview Video</button><button id="refreshPreviewButton" class="sf-button sf-button-secondary" type="button" hidden>Refresh Preview</button><a id="openPreviewPage" class="sf-button sf-button-secondary" href="#" target="_blank" rel="noopener">Open Preview Page</a></div>\n              <div class="sf-video-facts">')
rep('radio-admin/dev/social-factory/social-factory.js', "      'reviewStatusPill', 'publishStatusPill', 'videoPreview', 'previewLoading',\n      'videoRatio', 'videoDuration', 'videoSize', 'reviewForm', 'titleOptions',", "      'reviewStatusPill', 'publishStatusPill', 'videoPreview', 'previewLoading',\n      'previewVideoButton', 'refreshPreviewButton', 'openPreviewPage',\n      'videoRatio', 'videoDuration', 'videoSize', 'reviewForm', 'titleOptions',")
rep('radio-admin/dev/social-factory/social-factory.js', '    renderQueue();\n    loadPreview(item.id);\n  }', "    elements.videoPreview.pause();\n    elements.videoPreview.removeAttribute('src');\n    elements.videoPreview.load();\n    elements.previewLoading.hidden = false;\n    elements.previewLoading.textContent = 'Select Preview Video to create a secure 15-minute preview.';\n    elements.refreshPreviewButton.hidden = true;\n    elements.openPreviewPage.href = `https://stashbox.com/radio-admin/dev/social-factory/content-review/preview/?review_id=${encodeURIComponent(item.id)}`;\n    renderQueue();\n  }")
rep('radio-admin/dev/social-factory/social-factory.js', '      elements.videoPreview.src = payload.preview_url;\n      elements.videoPreview.load();\n      elements.previewLoading.hidden = true;', "      elements.videoPreview.src = payload.preview_url;\n      elements.videoPreview.load();\n      elements.previewLoading.hidden = true;\n      elements.refreshPreviewButton.hidden = false;\n      window.setTimeout(() => { if (state.selectedId !== id) return; elements.videoPreview.pause(); elements.videoPreview.removeAttribute('src'); elements.videoPreview.load(); elements.previewLoading.hidden = false; elements.previewLoading.textContent = 'This secure preview expired. Select Refresh Preview to create a new 15-minute preview.'; }, Number(payload.expires_in_seconds || 900) * 1000);")
rep('radio-admin/dev/social-factory/social-factory.js', "    elements.description.addEventListener('input', setCharacterCounts);\n    elements.videoPreview.addEventListener('error', () => {", "    elements.description.addEventListener('input', setCharacterCounts);\n    elements.previewVideoButton.addEventListener('click', () => state.selectedId && loadPreview(state.selectedId));\n    elements.refreshPreviewButton.addEventListener('click', () => state.selectedId && loadPreview(state.selectedId));\n    elements.videoPreview.addEventListener('error', () => {")
rep('social-factory-api/review-actions.mjs', "      return {\n        preview_url: previewUrl,\n        expires_in_seconds: PREVIEW_TTL_SECONDS,\n        content_type: String(item?.video?.content_type || 'video/mp4'),\n        file_name: String(item?.video?.file_name || '')\n      };", "      const reviewPageUrl = `https://stashbox.com/radio-admin/dev/social-factory/content-review/preview/?review_id=${encodeURIComponent(safeReviewId(reviewId))}`;\n      const isCustomGptRequest = Boolean(getHeader(event, 'authorization'));\n      return { ...(isCustomGptRequest ? {} : { preview_url: previewUrl }), review_page_url: reviewPageUrl, expires_in_seconds: PREVIEW_TTL_SECONDS, content_type: String(item?.video?.content_type || 'video/mp4'), file_name: String(item?.video?.file_name || '') };")
rep('custom-gpt/stashbox-radio/openapi.yaml', "      summary: Create or retrieve a secure preview for a review item.\n      parameters:\n        - $ref: '#/components/parameters/ReviewId'\n      responses:\n        '200':\n          description: Secure preview response.\n          content:\n            application/json:\n              schema:\n                $ref: '#/components/schemas/GenericResponse'", "      summary: Create a read-only secure reviewer link for a Content Review item.\n      description: Return review_page_url as the clickable reviewer link. Never display, quote, reproduce, or expose any temporary preview_url or storage credentials. This operation does not save, approve, hold, hide, schedule, stage, upload, publish, or change the review item.\n      parameters:\n        - $ref: '#/components/parameters/ReviewId'\n      responses:\n        '200':\n          description: Stable authenticated Stashbox reviewer page URL.\n          content:\n            application/json:\n              schema:\n                type: object\n                required: [ok, review_page_url, expires_in_seconds]\n                properties:\n                  ok: {type: boolean}\n                  review_page_url: {type: string, format: uri}\n                  expires_in_seconds: {type: integer, enum: [900]}\n                  content_type: {type: string}\n                  file_name: {type: string}\n                additionalProperties: false")
Path('social-factory-api/tests/secure-preview-contract.test.mjs').write_text("""import test from 'node:test';import assert from 'node:assert/strict';import {createReviewActionService} from '../review-actions.mjs';const id='render-c694a998-9548-46f3-b2c2-be194aacb2ef';function make(){let w=0;return{w:()=>w,s:createReviewActionService({secretStore:{async read(){return{admin_token:'t'}}},configSecretId:'x',store:{async getReview(){return{status:'in_review',approval_state:'pending',publishing_status:'not_published',metadata:{},publish_settings:{visibility:'unlisted',scheduled_at:null},video:{content_type:'video/mp4',file_name:'v.mp4'}}},async putReview(){w++},async createPreviewUrl(){return'https://signed/?credential=x'}}})}}const e=(x={})=>({headers:{'x-admin-token':'t',...x}});test('browser contract',async()=>{const x=make(),r=await x.s.preview(e(),id);assert.equal(r.expires_in_seconds,900);assert.ok(r.preview_url);assert.equal(r.review_page_url,`https://stashbox.com/radio-admin/dev/social-factory/content-review/preview/?review_id=${id}`);assert.equal(x.w(),0)});test('gpt omits signed url',async()=>{const x=make(),r=await x.s.preview(e({authorization:'Bearer g'}),id);assert.equal('preview_url'in r,false);assert.equal(x.w(),0)});test('auth',async()=>{const x=make();await assert.rejects(()=>x.s.preview({headers:{'x-admin-token':'bad'}},id),/unauthorized/);assert.equal(x.w(),0)});""")
